###
GET http://localhost:1300/api/v1/guests

###
GET http://localhost:1300/api/v1/guests/1

###
GET http://localhost:1300


###
GET http://localhost:1300/setup

###
POST http://localhost:1300/api/v1/guests
Content-Type: application/json

{
    "first_name" : "fnamooo",
    "last_name" : "lnamooo",
    "email" : "foo3@bar.com"
} 