###
GET http://localhost:1300/api/v1/guests

###
GET http://localhost:1300/api/v1/guests/2


###
DELETE  http://localhost:1300/api/v1/guests/2

###
GET http://localhost:1300


###
POST http://localhost:1300/api/v1/guests
Content-Type: application/json

{
    "first_name" : "actual",
    "last_name" : "second",
    "email" : "aaa@bafr.com",
    "phone_numbers" : ["1234","4567"]
} 

###
PUT http://localhost:1300/api/v1/guests
Content-Type: application/json

{
    "user_id" : 1,
    "first_name" : "alo",
    "last_name" : "marhaba",
    "email" : "daaaddsf@bafr.com",
    "phone_numbers" : ["wqerw","4567qerwq"]
} 

### ROOM

### get rooms
GET http://localhost:1300/api/v1/rooms

### create room
POST http://localhost:1300/api/v1/rooms
Content-Type: application/json 

{
    "room_number": "222",
    "room_type_id" : "2"
}

### update room
PUT  http://localhost:1300/api/v1/rooms/1
Content-Type: application/json 

{
    "room_number": "111111",
    "room_type_id" : "2"
}

### delete room
DELETE http://localhost:1300/api/v1/rooms/1

### get rooms with filters
GET http://localhost:1300/api/v1/rooms?offset=10&limit=20

### get all reservations for a room
GET http://localhost:1300/api/v1/rooms/reservations/3

### ROOM TYPES
POST http://localhost:1300/api/v1/rooms/room_types
Content-Type: application/json 

{
    "type": "custom_room_type",
    "price" : 800000
}

###

GET http://localhost:1300/api/v1/rooms/room_types

###

GET http://localhost:1300/api/v1/reservations

### 
POST http://localhost:1300/api/v1/reservations
Content-Type: application/json 

{
   "room_ids" : [1],
   "guest_id" : 1,
"start_date": "2025-01-20",
    "end_date": "2025-01-25"
}

