services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: hardPassword
    ports:
      - "5432:5432"

  api:
    container_name: express-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1300:3000
  frontend:
    container_name: angular-frontend
    build:
      context: ./frontend/avant_frontend
    ports:
      - 4200:80
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5959:80"
    depends_on:
      - postgres_db
