import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    await knex('guests').del()

    await knex('guests').insert([
        { first_name: 'peach_F', last_name: 'peach_L', email: "peach@foobar.com" },
        { first_name: 'bowser_F', last_name: 'bowser_L', email: "bowser@foobar.com" },
        { first_name: 'mario_F', last_name: 'mario_L', email: "mario@foobar.com" },
        { first_name: 'luigi_F', last_name: 'luigi_L', email: "luigi@foobar.com" },
        { first_name: 'toad_F', last_name: 'toad_L', email: "toad@foobar.com" },
        { first_name: 'yoshi_F', last_name: 'yoshi_L', email: "yoshi@foobar.com" },
        { first_name: 'daisy_F', last_name: 'daisy_L', email: "daisy@foobar.com" },
        { first_name: 'rosalina_F', last_name: 'rosalina_L', email: "rosalina@foobar.com" },
        { first_name: 'waluigi_F', last_name: 'waluigi_L', email: "waluigi@foobar.com" },
        { first_name: 'wario_F', last_name: 'wario_L', email: "wario@foobar.com" },
        { first_name: 'koopa_F', last_name: 'koopa_L', email: "koopa@foobar.com" },
        { first_name: 'shyGuy_F', last_name: 'shyGuy_L', email: "shyguy@foobar.com" },
        { first_name: 'birdo_F', last_name: 'birdo_L', email: "birdo@foobar.com" },
        { first_name: 'hammerBro_F', last_name: 'hammerBro_L', email: "hammerbro@foobar.com" },
        { first_name: 'kingBoo_F', last_name: 'kingBoo_L', email: "kingboo@foobar.com" },
        { first_name: 'goomba_F', last_name: 'goomba_L', email: "goomba@foobar.com" },
        { first_name: 'lakitu_F', last_name: 'lakitu_L', email: "lakitu@foobar.com" },
        { first_name: 'dryBones_F', last_name: 'dryBones_L', email: "drybones@foobar.com" },
        { first_name: 'boo_F', last_name: 'boo_L', email: "boo@foobar.com" },
        { first_name: 'bulletBill_F', last_name: 'bulletBill_L', email: "bulletbill@foobar.com" },
        { first_name: 'magikoopa_F', last_name: 'magikoopa_L', email: "magikoopa@foobar.com" },
        { first_name: 'piranhaPlant_F', last_name: 'piranhaPlant_L', email: "piranhaplant@foobar.com" },
        { first_name: 'turtle_F', last_name: 'turtle_L', email: "turtle@foobar.com" },
        { first_name: 'thwomp_F', last_name: 'thwomp_L', email: "thwomp@foobar.com" },
        { first_name: 'chainChomp_F', last_name: 'chainChomp_L', email: "chainchomp@foobar.com" },
        { first_name: 'wiggler_F', last_name: 'wiggler_L', email: "wiggler@foobar.com" },
        { first_name: 'fuzzy_F', last_name: 'fuzzy_L', email: "fuzzy@foobar.com" },
        { first_name: 'kamek_F', last_name: 'kamek_L', email: "kamek@foobar.com" },
        { first_name: 'nabbit_F', last_name: 'nabbit_L', email: "nabbit@foobar.com" },
        { first_name: 'rosalina_F', last_name: 'rosalina_L', email: "rosalina2@foobar.com" },
        { first_name: 'donkeyKong_F', last_name: 'donkeyKong_L', email: "donkeykong@foobar.com" },
        { first_name: 'diddyKong_F', last_name: 'diddyKong_L', email: "diddykong@foobar.com" },
        { first_name: 'funkyKong_F', last_name: 'funkyKong_L', email: "funkykong@foobar.com" },
        { first_name: 'babyMario_F', last_name: 'babyMario_L', email: "babymario@foobar.com" },
        { first_name: 'babyLuigi_F', last_name: 'babyLuigi_L', email: "babyluigi@foobar.com" },
        { first_name: 'babyPeach_F', last_name: 'babyPeach_L', email: "babypeach@foobar.com" },
        { first_name: 'babyDaisy_F', last_name: 'babyDaisy_L', email: "babydaisy@foobar.com" },
        { first_name: 'metalMario_F', last_name: 'metalMario_L', email: "metalmario@foobar.com" },
    ]);
};
